---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-blue
  labels:
    app: swiggy
    env: blue
spec:
  replicas: 2
  selector:
    matchLabels:
       app: swiggy
       env: blue
  template:
    metadata:
      labels:
        app: swiggy
        env: blue
    spec: 
      containers:
        - name: cont1
          image: reddy0314/images:v1
          ports:
            - containerPort: 3000 
          
