---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  replicas: 2
  selector:
    matchLabels:
       app: swiggy
  template:
    metadata:
      labels:
        app: swiggy
    spec: 
      containers:
        - name: cont1
          image: reddy0314/images:game
          ports:
            - containerPort: 3000 
          
